Syslog
| where SyslogMessage has 'deny'
| extend src= extract("(([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})\\.(([0-9]{1,3})))",0,SyslogMessage) 
| extend destinationTranslatedAddress = extract("(([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})\\.(([0-9]{1,3})))",0,SyslogMessage) 
| extend suser = extract ()
| summarize Denials=count()by bin(TimeGenerated, 10m)
| extend AccountCustomEntity = UserName
| extend FileCustomEntity = SrcFileName, AccountCustomEntity = DstUsername
